### ISSUE TITLE
CI/CD Data Services API

### ISSUE THREAD

**Issue by darthtrevino** [microsoft/covid-vaccine-bot#37]
- [x] Push data to Azure Storage (Derek)
- [x] Push data to HealthBot over REST APIs
- [ ] Set up backup/restore tools over CLI using REST APIs
- [ ] Red/Green Prod Environment

**Comment by barneaoren** [comment]
As of Jan 31st 2021, A new set of management APIs were activated for the Microsoft Healthcare Bot Service to support this specific effort

GET /backup - create a new backup
POST /backup - deploy a backup
GET /resources - get the list of resources
POST /resources - publish new resources
DELETE /resources - remove set of existing resources

A sample repo with examples how to use those APIs can be found here

https://github.com/barneaoren/HealthBotServiceManagementAPI
